---
name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15
      - name: Cache derived data
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ hashFiles('**/*.{swift,objc,h,m}') }}
          restore-keys: |
            ${{ runner.os }}-derived-data-
      - name: Build Project for testing
        run: |
          xcodebuild build-for-testing \
          -project NanoChallenge07/NanoChallenge07.xcodeproj \
          -scheme NanoChallenge07 \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro'
      - name: Run tests
        run: |
          xcodebuild test \
          -project NanoChallenge07/NanoChallenge07.xcodeproj \
          -scheme NanoChallenge07 \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro'
      - name: Run regular build
        run: |
           xcodebuild build \
           -project NanoChallenge07/NanoChallenge07.xcodeproj \
           -scheme NanoChallenge07 \
           -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
           CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty
